version: "3.9"
services:
  web:
    build: .
    ports:
      - "5368:5369"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mariadb:3306/mesi?serverTimezone=UTC",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.hibernate.naming.physical-strategy" : "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      }'
    depends_on:
      - mariadb
  mariadb:
    build: .\src\main\resources\db\
    container_name: mesimariadb
    ports:
    - "127.0.0.1:3307:3306"
